#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean all basic || exit 1
wclean all electromagnetics || exit 1
wclean all heatTransfer || exit 1
wclean all incompressible || exit 1
wclean all multiphase || exit 1
wclean all surfaceTracking || exit 1

wclean all multiPhysics || exit 1
