#!/bin/sh

. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanFaMesh ()
{
    rm -rf ./constant/faMesh/faceLabels* \
           ./constant/faMesh/faBoundary* \
           > /dev/null 2>&1
}

cleanHistoryFolder ()
{
    rm -rf ./history \
        > /dev/null 2>&1
}

cleanHistoryFolder
cleanTimeDirectories
cleanFaMesh

find -name *Map -delete > /dev/null 2>&1
find -name *Map.gz -delete > /dev/null 2>&1
find -name *Addressing -delete > /dev/null 2>&1
find -name *Addressing.gz -delete > /dev/null 2>&1
find -name *RegionToRegionAddressing -delete > /dev/null 2>&1
find -name *RegionToRegionAddressing.gz -delete > /dev/null 2>&1

rm -rf processor* > /dev/null 2>&1
rm -rf system/region0_faSubMesh > /dev/null 2>&1
rm -rf constant/region0_faSubMesh > /dev/null 2>&1
